export const texts = {
  pt: {
    submissions: "Submissões",
    register: "Inscrever-se",
    schedule: "Programação",
    event: "Evento",
    works: "Trabalhos",
    edition: "Edição 2024",
    exposanea: "Exposanea",
    programming: "Programação",
    contact: "Contato",
  },
  en: {
    submissions: "Submissions",
    register: "Register",
    schedule: "Schedule",
    event: "Event",
    works: "Works",
    edition: "2024 Edition",
    exposanea: "Exposanea",
    programming: "Programming",
    contact: "Contact",
  },
  es: {
    submissions: "Envíos",
    register: "Registrarse",
    schedule: "Horario",
    event: "Evento",
    works: "Trabajos",
    edition: "Edición 2024",
    exposanea: "Exposanea",
    programming: "Programación",
    contact: "Contacto",
  },
};
