import { register } from "swiper/element";

export const texts = {
  pt: {
    event: "Evento",
    date: "Data e Local",
    hosting: "Hospedagem",
    edition: "Edição 2024",
    programming: "Programação",
    painels: "Painéis temáticos",
    miniCourse: "Minicurso",
    visit: "Visitas técnicas",
    speakers: "Palestrantes",
    submissions: "Submissões",
    modelApresentation: "Modelo de apresentação",
    modelEposter: "Modelo e-poter",
    exposanea: "Exposânea",
    exhibitors: "Expositores",
    register: "Inscrições",
    information: "Informações",
  },
  en: {
    event: "Event",
    date: "Date and Location",
    hosting: "Hosting",
    edition: "2024 Edition",
    programming: "Programming",
    painels: "Thematic Panels",
    miniCourse: "Minicourse",
    visit: "Technical Visits",
    speakers: "Speakers",
    submissions: "Submissions",
    modelApresentation: "Presentation Model",
    modelEposter: "E-poster Model",
    exposanea: "Exposanea",
    exhibitors: "Exhibitors",
    register: "Registration",
    information: "Information",
  },
  es: {
    event: "Evento",
    date: "Fecha y Lugar",
    hosting: "Alojamiento",
    edition: "Edición 2024",
    programming: "Programación",
    painels: "Paneles temáticos",
    miniCourse: "Minicurso",
    visit: "Visitas técnicas",
    speakers: "Conferencistas",
    submissions: "Envíos",
    modelApresentation: "Modelo de presentación",
    modelEposter: "Modelo de e-póster",
    exposanea: "Exposanea",
    exhibitors: "Expositores",
    register: "Registro",
    information: "Información",
  },
};
